[package]
name = "bot_rust_discord"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
serenity = "0.11"
dotenv = "0.15.0"
tempfile = "3.2.0"
tokio = { version = "1.21.2", features = ["full"] }